export const BOOTCAMP_CURRICULUM = [
  { day: 1, title: "The Foundation", focus: "Vivid Imagery", itemCount: 3, cleaning: false, reverse: false },
  { day: 2, title: "The Expansion", focus: "Making Space", itemCount: 5, cleaning: true, reverse: false },
  { day: 3, title: "The Reverse", focus: "Mental Agility", itemCount: 5, cleaning: true, reverse: true },
  { day: 4, title: "The Stretch", focus: "Volume", itemCount: 8, cleaning: true, reverse: false },
  { day: 5, title: "The Graduation", focus: "Mastery", itemCount: 10, cleaning: true, reverse: true },
  { day: 6, title: "The Deepening", focus: "Vivid Imagery", itemCount: 8, cleaning: false, reverse: false },
  { day: 7, title: "The Layering", focus: "Making Space", itemCount: 8, cleaning: true, reverse: false },
  { day: 8, title: "The Architecture", focus: "Mental Agility", itemCount: 8, cleaning: true, reverse: true },
  { day: 9, title: "The Navigator", focus: "Volume", itemCount: 8, cleaning: true, reverse: false },
  { day: 10, title: "The Double Down", focus: "Mastery", itemCount: 8, cleaning: true, reverse: true },
  { day: 11, title: "The Double Digits", focus: "Vivid Imagery", itemCount: 10, cleaning: false, reverse: false },
  { day: 12, title: "The Long Walk", focus: "Making Space", itemCount: 10, cleaning: true, reverse: false },
  { day: 13, title: "The Challenger", focus: "Mental Agility", itemCount: 10, cleaning: true, reverse: true },
  { day: 14, title: "The Stamina", focus: "Volume", itemCount: 10, cleaning: true, reverse: false },
  { day: 15, title: "The Milestone", focus: "Mastery", itemCount: 10, cleaning: true, reverse: true },
  { day: 16, title: "The Momentum", focus: "Vivid Imagery", itemCount: 10, cleaning: false, reverse: false },
  { day: 17, title: "The Discipline", focus: "Making Space", itemCount: 10, cleaning: true, reverse: false },
  { day: 18, title: "The Flow", focus: "Mental Agility", itemCount: 10, cleaning: true, reverse: true },
  { day: 19, title: "The Refinement", focus: "Volume", itemCount: 10, cleaning: true, reverse: false },
  { day: 20, title: "The Veteran", focus: "Mastery", itemCount: 10, cleaning: true, reverse: true },
  { day: 21, title: "The Expert", focus: "Vivid Imagery", itemCount: 12, cleaning: false, reverse: false },
  { day: 22, title: "The Twelve", focus: "Making Space", itemCount: 12, cleaning: true, reverse: false },
  { day: 23, title: "The Endurance", focus: "Mental Agility", itemCount: 12, cleaning: true, reverse: true },
  { day: 24, title: "The Architect", focus: "Volume", itemCount: 12, cleaning: true, reverse: false },
  { day: 25, title: "The Quarter Century", focus: "Mastery", itemCount: 12, cleaning: true, reverse: true },
  { day: 26, title: "The Persistence", focus: "Vivid Imagery", itemCount: 12, cleaning: false, reverse: false },
  { day: 27, title: "The Champion", focus: "Making Space", itemCount: 12, cleaning: true, reverse: false },
  { day: 28, title: "The Precision", focus: "Mental Agility", itemCount: 12, cleaning: true, reverse: true },
  { day: 29, title: "The Legend", focus: "Volume", itemCount: 12, cleaning: true, reverse: false },
  { day: 30, title: "The Summit", focus: "Mastery", itemCount: 12, cleaning: true, reverse: true },
];
